language: c
install:
- sudo apt-get install mono-devel mono-gmcs nunit-console
- mozroots --import --ask-remove
script:
- cd CKAN
- xbuild CKAN.sln
- nunit-console Tests/bin/Debug/Tests.dll
before_deploy:
- cd ..
- mkdir uploads
- bin/build
- cp ckan.exe uploads/ckan-`git describe --long`.exe
deploy:
  provider: releases
  api_key:
    secure: CABnGmJltXYhLHUX7M72QLkihqT0VY6A1oEg18jZfZncmvPZWklz5XFuLUkVx4wXcFfusi5dm5mVHuhKiVmyOCfFd6DXxkpGePXHX4dTjrSPYEp06nwWgYIb0K2Z8FNKZN/qUYntunoviVHYHyIhHMvELlEwC3Qez/Bkhrx5Kls=
  file: ckan.exe
  on:
    repo: pjf/CKAN
